language: scala
scala:
- 2.12.2
jdk:
- oraclejdk8
sudo: false
addons:
  apt:
    packages:
    - graphviz
install:
- pip install --user codecov
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/"
after_success:
- codecov
